Update index.rst
lcdb/lcdb-wf pull request #321
Opened 2020-11-25 23:14 UTC by evajason

Made a few changes for clarity.

2020-12-17 02:15 UTC, daler requested changes
Thanks! Minor suggestions below.

2020-12-17 02:15 UTC, daler commented on docs/faqs.rst
> +alone. Samples that need to treated differently should be split off into
```suggestion
There is no mechanism for specifying sample-specific parameters. For example,
to use cutadapt to trim some 5' bases from some samples but leave other samples alone.
Samples that need to treated differently should be split off into
```

2020-12-17 02:15 UTC, daler commented on docs/getting-started.rst
> +There are many additional files (like these docs) and esting files that are not
```suggestion
There are many additional files (like these docs) and testing files that are not
```

2021-01-27 14:43 UTC, evajason commented
The list in the [ChIP-seq workflow](https://github.com/lcdb/lcdb-wf/blame/eva-edits/docs/chipseq.rst#L9-L29)does not match the tense of the sentence before. Maybe change "does" to "will do".

2021-01-27 14:43 UTC, evajason commented
I think the example [here](https://github.com/lcdb/lcdb-wf/blame/master/docs/faqs.rst#L92-L94) shouldn't be in parenthesis. Seems like important information.

2021-01-27 14:44 UTC, evajason commented
missing [list] (https://github.com/lcdb/lcdb-wf/blame/master/docs/config-yaml.rst#L532) of other peak callers in config-yaml.rst

2021-01-27 17:21 UTC, evajason commented
Give examples for ["custom parameters"] (https://github.com/lcdb/lcdb-wf/blame/master/docs/faqs.rst#L100-L101). Are these multiple IP and input labels? I was looking in the (config-yaml.rst)[https://lcdb.github.io/lcdb-wf/config-yaml.html#config-yaml] and it wasn't clear to me what "custom parameters" refers. But, I have also never used the ChIP-seq workflow so that might also be why it isn't clear to me.

2021-01-28 17:35 UTC, evajason commented
[This](https://github.com/lcdb/lcdb-wf/blame/eva-edits/docs/patterns-targets.rst#L24-L28) could be clearer. I would swap around the order of the sentence:

The metadata configured in the sample table and config file fills in those patterns to create the **targets**.

Because the patterns already exist, the user fills in the metadata, and then the targets are created, right?

2021-01-28 18:09 UTC, evajason commented
In [patterns-targets.rst](https://github.com/lcdb/lcdb-wf/blob/eva-edits/docs/patterns-targets.rst#L24-L28) it has both "sample table" and "sampletable" written. It should probably be "sample table" unless directly referring to the sampletable.tsv within the workflow.

2021-02-01 14:08 UTC, evajason commented
I think the [Unified approach to references](https://github.com/lcdb/lcdb-wf/blame/eva-edits/docs/index.rst#L38-L46) section is confusing and repetitive. I suggest switching the order to explain the reference wf first. No need to repeat that it's made for customization because that's the first thing on this page. 

Unified approach to references

This system is designed to include arbitrary genomes whether local or on the web. The references workflow is shared by RNA-seq and ChIP-seq and is driven by a config file that specifies URLs for FASTA and GTF files. Set it up once for a website to get lots of genomes you can use for running fastq_screen, and easily include arbitrary other genomes. They can then be automatically included in RNA-seq and ChIP-seq workflows. The references_dir is used as a centralized repository that can be included with all other future projects.

2021-03-02 20:29 UTC, closed without merging